version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
        VITE_STORAGE_PREFIX: ${VITE_STORAGE_PREFIX:-todo-app}
        VITE_ENABLE_LOGGING: ${VITE_ENABLE_LOGGING:-false}
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Uncomment for SSL
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - production
